### PR TITLE
Meet

### PR DESCRIPTION
**Pull request by Meetdhola**
Add photo in gallery section
Screenshot 2024-02-01 at 7 46 51 PM

### CODE REVIEW

**Review by nssbvm — CHANGES_REQUESTED** [review]
Use external css instead of internal. Add external css to style.css. if there are conflicts then create new css file and link to html

**Comment by Meetdhola** [comment]
Okay I can Understand.

**Comment by nssbvm** [comment]
Why did you close this Pull request?

**Review by nssbvm — CHANGES_REQUESTED** [review]
Design looks bit odd. thodak cards na shadow ma changes kari aap and make sure the page is responsive and all photos be aligned on any screen size

**Comment by nssbvm** [comment]
And Don't close this pull request this time I will check review it and then I will merge it. You just only have to create pull request, You don't have to merge. If some conficts occur then only you close this PR with appropriate reason

**Comment by Meetdhola** [comment]
Okay

**Comment by Meetdhola** [comment]
Responsiveness added and change in box-shadow
Screenshot 2024-02-10 at 3 48 39 PM

**Comment by nssbvm** [comment]
Give it a title(Gallery Section) inside the section and cards mota kari naakh, photos nana laage che, baaki badhu barobar and proper che

**Comment by Meetdhola** [comment]
Big photo size
Screenshot 2024-02-15 at 8 13 31 PM

**Review by nssbvm — APPROVED** [review]

**Pull request merged**
